In [1]:
import numpy as np
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [5]:
ch_arr2=np.array(["Supervised","unSupervised","sEMI-supervised","reinforcement"])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')

In [6]:
cleaned_arr=np.char.replace(low_arr,"-"," ")
cleaned_arr

array(['supervised', 'unsupervised', 'semi supervised', 'reinforcement'],
      dtype='<U15')

In [11]:
array1=np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [12]:
array1.dtype

dtype('int32')

In [13]:
char_arr.dtype

dtype('<U1')

In [14]:
low_arr.dtype


dtype('<U15')

In [16]:
array8=np.array([1,2,3,4,5],dtype='f')

In [17]:
array8

array([1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
array8=np.array([1,2,3,4,5],dtype='float64')

In [19]:
array8.dtype

dtype('float32')

In [20]:
array2conv=array8.astype('f')
array2conv

array([1., 2., 3., 4., 5.], dtype=float32)

In [21]:
array7conv=array8.astype('i')
array7conv

array([1, 2, 3, 4, 5], dtype=int32)

In [22]:
array7conv=array8.astype('c')
array7conv

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [26]:
array2conv=array8.astype('S')
array2conv

array([b'1.0', b'2.0', b'3.0', b'4.0', b'5.0'], dtype='|S32')

In [27]:
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [28]:
char_conv=char-arr.astype('i')
char_conv

NameError: name 'char' is not defined

In [33]:
ars1=np.ones(2)
ars1

array([1., 1.])

In [34]:
ars1=np.zeros(4)
ars1

array([0., 0., 0., 0.])

In [36]:
ars1=np.random.random(2)
ars1

array([0.72024955, 0.70512187])

numone=np.ones((2,2),dtype=int)

In [37]:
numone=np.ones((2,2),dtype=int)
numone

array([[1, 1],
       [1, 1]])

In [40]:
numone=np.ones((3,2),dtype=int)
numone

array([[1, 1],
       [1, 1],
       [1, 1]])

In [39]:
numsone=np.ones((3,2))
numsone

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
numsone=np.zeros((3,2))
numsone

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [42]:
dimones=np.ones((4,3,2))

In [44]:
dimones.ndim

3

In [46]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
#addition
addition=ar1+ar2
print("addition:\n",addition)

addition:
 [[ 6  8 10]
 [12 14 16]]


In [47]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
#Substraction
addition=ar1-ar2
print("addition:\n",addition)

addition:
 [[-4 -4 -4]
 [-4 -4 -4]]


In [48]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
#Multiplication
addition=ar1*ar2
print("addition:\n",addition)

addition:
 [[ 5 12 21]
 [32 45 60]]


In [49]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
#Division
addition=ar1/ar2
print("addition:\n",addition)

addition:
 [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [51]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
#addition
addition=ar1+ar2
substraction=ar1-ar2
multiplication=ar1*ar2
division=ar1/ar2
print("addition:\n",addition)
print("Substraction:\n",substraction)
print("Multiplication:\n",multiplication)
print("Divison:\n",division)

addition:
 [[ 6  8 10]
 [12 14 16]]
Substraction:
 [[-4 -4 -4]
 [-4 -4 -4]]
Multiplication:
 [[ 5 12 21]
 [32 45 60]]
Divison:
 [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [52]:
power=np.power(ar1,ar2)
print("power:\n",power)

power:
 [[       1       64     2187]
 [   65536  1953125 60466176]]


In [53]:
array2d=np.array([[1,2,3],[4,5,6]])
array1d=np.array([10,20,22])
#add 1d array to 2d array
result=array2d+array1d
result

array([[11, 22, 25],
       [14, 25, 28]])

In [55]:
range_array=np.arange(0,10,3)
range_array

array([0, 3, 6, 9])

In [ ]:
size:int or tuple of ints,optional:The shape of the array yoy want to create

In [61]:
b=np.random.randint(low=1,high=6,size(2,3))


SyntaxError: positional argument follows keyword argument (752498422.py, line 1)

In [59]:
b

NameError: name 'b' is not defined

In [63]:
np.concatenate([ar1,ar2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [71]:
flatarr=ar1.flatten()
flatarr

array([1, 2, 3, 4, 5, 6])

In [72]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [73]:
np.info(np.ndarray.ndim)

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3


In [74]:
import matplotlib.pyplot as plt
from scipy import stats